### ISSUE TITLE
测试工程运行的问题

### ISSUE THREAD

**Issue by yinhualong** [laziobird/opentelemetry-jaeger#3]
你好，感谢您提供的学习工程，特别在中文圈。
我在运行学习的过程中，测试http://127.0.0.1:8080/loadBalancer?tag=test接口，trace生成成功！查看完整链路图，traceId: [00000000000000000000000000000000](http://127.0.0.1:8080/getTrace?traceId=00000000000000000000000000000000)
![微信图片_20220504011628](https://user-images.githubusercontent.com/50351296/166505197-4b87bcfd-1a96-4ae4-95dc-d71f45b9e3c7.png)

http://127.0.0.1:8080/resource?tag=error 接口时：
![image](https://user-images.githubusercontent.com/50351296/166505397-7a4f8c16-2ab3-487a-918a-f3f8d00d446b.png)

,运行的时候没有启动收集应用。麻烦得空的时候帮忙解答一下，感谢

**Comment by laziobird** [comment]
![issue3](https://user-images.githubusercontent.com/16099500/166621025-5e6d27ba-cc79-4baa-af50-813aeabe05a2.png)
这个 程序没有问题。Demo 在Baggage里面存的全局tag 和取的tag 不是一个key，你可以源代码写个新的用例，获取`baggage.key` 就能拿到值了

**Comment by yinhualong** [comment]
感谢
